name: graphein
channels:
- pytorch
- pytorch3d
- dglteam
- conda-forge
- anaconda
- bioconda
- fvcore
- iopath
- plotly
- schrodinger
- salilab
- rusty1s
dependencies:
- python=3.8
- biopython
- biopandas
- conda
- dgl
- dssp
- fvcore
- ipympl
- iopath
- mamba
- matplotlib
- anaconda::multipledispatch
- mypy
- networkx
- nodejs
- numpy
- pandas
- pandoc
- pip
- plotly
- pydantic
- pymol
- pyyaml
- scikit-learn
- scipy
- tqdm
- pytorch
- pytorch3d
- pytorch-geometric
- pytorch-lightning
- torchvision
- versioneer
- python-wget
- xarray
- pip:
  - nbgitpuller
  - biovec
  - propy3
  - pyaaisc
  - graphein

